name: Flutter CI

# This workflow is triggered on click of button

on:
  workflow_dispatch

    
jobs:
  windows:
    name: create windows executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter channel dev
      - run: flutter config --enable-windows-desktop
      - run: flutter create --platforms=windows .
      - run: flutter devices
      - run: flutter pub get
      - run: flutter build windows --release
      - run: flutter pub run msix:create
      - run: tree
    
      # Upload generated files.
      - uses: actions/upload-artifact@v1
        with:
          name: application
          path: windows/
